tier-1:
  pos1:
    x: 0
    y: 0
    z: 0
  pos2:
    x: 0
    y: 0
    z: 0

tier-2:
  pos1:
    x: 0
    y: 0
    z: 0
  pos2:
    x: 0
    y: 0
    z: 0

tier-3:
  pos1:
    x: 0
    y: 0
    z: 0
  pos2:
    x: 0
    y: 0
    z: 0

tier-4:
  pos1:
    x: 0
    y: 0
    z: 0
  pos2:
    x: 0
    y: 0
    z: 0

tier-5:
  pos1:
    x: 0
    y: 0
    z: 0
  pos2:
    x: 0
    y: 0
    z: 0